import { CreditReport, Transaction } from '@/types';

const REPORTS_STORAGE_KEY = 'credit_reports_db';
const TRANSACTIONS_STORAGE_KEY = 'transactions_db';

// Helper to get all reports from storage
export function getAllReports(): CreditReport[] {
  try {
    const stored = sessionStorage.getItem(REPORTS_STORAGE_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}

// Helper to save a report
export function saveReport(report: CreditReport): void {
  const existing = getAllReports();
  // Check for duplicate by ID
  const existingIndex = existing.findIndex(r => r.id === report.id);
  if (existingIndex >= 0) {
    existing[existingIndex] = report;
  } else {
    existing.unshift(report);
  }
  sessionStorage.setItem(REPORTS_STORAGE_KEY, JSON.stringify(existing));
}

// Get report by ID
export function getReportById(reportId: string): CreditReport | null {
  const reports = getAllReports();
  return reports.find(r => r.id === reportId) || null;
}

// Check if report is unlocked (from stored state)
export function isReportUnlocked(reportId: string): boolean {
  const report = getReportById(reportId);
  return report?.report_status === 'UNLOCKED';
}

// Update report status
export function updateReportStatus(reportId: string, status: 'LOCKED' | 'UNLOCKED'): void {
  const reports = getAllReports();
  const report = reports.find(r => r.id === reportId);
  if (report) {
    report.report_status = status;
    sessionStorage.setItem(REPORTS_STORAGE_KEY, JSON.stringify(reports));
  }
}

// Get reports for a specific user
export function getReportsByUser(userEmail: string): CreditReport[] {
  return getAllReports().filter(r => r.user_email === userEmail);
}

// Get reports generated by a partner
export function getReportsByPartner(partnerId: string): CreditReport[] {
  return getAllReports().filter(r => r.partner_id === partnerId);
}

// Get unlocked reports only
export function getUnlockedReports(): CreditReport[] {
  return getAllReports().filter(r => r.report_status === 'UNLOCKED');
}

// Transaction helpers
export function getAllTransactions(): Transaction[] {
  try {
    const stored = sessionStorage.getItem(TRANSACTIONS_STORAGE_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}

export function saveTransaction(transaction: Transaction): void {
  const existing = getAllTransactions();
  const existingIndex = existing.findIndex(t => t.id === transaction.id);
  if (existingIndex >= 0) {
    existing[existingIndex] = transaction;
  } else {
    existing.unshift(transaction);
  }
  sessionStorage.setItem(TRANSACTIONS_STORAGE_KEY, JSON.stringify(existing));
}

// Initialize storage with mock data if empty
export function initializeStorageWithMockData(
  mockReports: CreditReport[],
  mockTransactions: Transaction[]
): void {
  if (getAllReports().length === 0 && mockReports.length > 0) {
    sessionStorage.setItem(REPORTS_STORAGE_KEY, JSON.stringify(mockReports));
  }
  if (getAllTransactions().length === 0 && mockTransactions.length > 0) {
    sessionStorage.setItem(TRANSACTIONS_STORAGE_KEY, JSON.stringify(mockTransactions));
  }
}
